production:
  searchd_file_path: "/home/production/app/shared/sphinx"
  # searchd_log_file: "RAILS_ROOT/log/searchd.log"
  # query_log_file: "RAILS_ROOT/log/searchd.query.log"
  morphology: stem_ru
development:
  searchd_file_path: "/home/dev/yapropal/app/shared/sphinx"
  # searchd_log_file: "RAILS_ROOT/log/searchd.log"
  # query_log_file: "RAILS_ROOT/log/searchd.query.log"
  morphology: stem_ru
test:
  searchd_file_path: "/home/dev/yapropal/app/shared/sphinx"
